# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Reading KeyVault Secrets
      id: ReadKeyVault
      run: |
        InActiveDatabaseUrl=$(az keyvault secret show --name "InActive-database-url" --vault-name "parteyKeyVault1" --query "value" --output tsv)
        echo "::set-output name=InActiveDatabaseUrl::$InActiveDatabaseUrl"
      
    - name: PowershellScript
      run: |
            $test = "${{ steps.ReadKeyVault.outputs.InActiveDatabaseUrl }}"
            Write-Host $test
            Write-Host $test.Substring(0, $test.IndexOf("."))
            Write-Host "Line 3"
      shell: pwsh

    # - name: Printing KeyVault Secrets
    #   run: |          
    #       echo "${{ steps.ReadKeyVault.outputs.InActiveDatabaseUrl }}"          
    #   env: #Set secrets as environment variables
    #     In_ActiveDatabase_Url: ${{ steps.ReadKeyVault.outputs.InActiveDatabaseUrl }}

    # - name: Run Azure PowerShell script
    #   uses: azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       Write-Output  $Env:In_ActiveDatabase_Url
    #     azPSVersion: "latest"
      
    # - name: Stopping Postgres Server
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.30.0
    #     inlineScript: |
    #       az postgres flexible-server stop  --resource-group rgManish --name ${{ steps.ReadKeyVault.outputs.InActiveDatabaseUrl }}.Substring(0, ${{ steps.ReadKeyVault.outputs.InActiveDatabaseUrl }}.IndexOf("."))
